@startuml

package Entity <<Database>> {
    class User {
        {static} Auto_increment id
        --
        {static} String name
        {static} String email
        {static} String password
        {static} Json roles
        {static} Datetime created_at
        {static} Datetime updated_at
    }

    Task "0..*" -- "1" User

    class Task {
        {static} Auto_increment id
        --
        {static} String title
        {static} String content
        {static} Datetime created_at
        {static} String is_done
        {static} String user_id
    }
}

@enduml
