@startuml

scale 1
Left to right direction
skinparam packageStyle rect
actor Admin
actor User

rectangle cas_d'utilisation {
    Admin --|> User

    package Users {
        User -- (s'authentifier)
    }

    package Tasks {
        User -- (creer une tâche)
        User -- (modifier/supprimer une tâche)
    }

    package Administration {
        Admin -- (voir la liste des utilisateurs)
        Admin -- (voir les details d'un utilisateur)
        Admin -- (modifier un utilisateur)
        Admin -- (creer un compte)
    }


    Administration ..> (s'authentifier):include
    Tasks ..> (s'authentifier):include

    (voir les details d'un utilisateur) .> (modifier un utilisateur) :extend
}

@enduml
