@startuml details_utilisateurs

actor Administrateur
boundary Systeme
database BDD

note left of Administrateur: l'administrateur doit etre authentifié

Administrateur -> Systeme: afficher les details d'un utilisateur
Systeme -> BDD: recherche de l'utilisateur
BDD --> Systeme : utilisateur trouvé
Systeme --> Administrateur: Page details de l'utilisateur

@enduml
