@startuml lister_les_utilisateurs

actor Administrateur
boundary Systeme
database BDD

note left of Administrateur: l'administrateur doit etre authentifié

Client -> Systeme: afficher la liste des utilisateurs
Systeme -> BDD: recherche des utilisateurs
BDD --> Systeme : utilisateurs trouvés
Systeme --> Client: page affichant la liste des utilisateurs

@enduml
