@startuml modifier_ou_supprimer_une_tache

actor User
boundary Systeme
database BDD

note left of User: l'utilisateur doit etre authentifié

User -> Systeme : demande d'accès à la page de modification de la tache

alt la tache appartient a l'utilisateur OU (la tache est anonyme et l'utilisateur est un admin)
    Systeme -> BDD: recherche de la tache
    BDD --> Systeme : tache trouvée
    Systeme --> User: page de modification de la tache

    User -> Systeme : nouvelles données de la tache
    Systeme -> BDD: enregistrement de la tache
    BDD --> Systeme : tache trouvée
    Systeme --> User: retour page principal avec message de confirmation

else la tache n'appartient pas a l'utilisateur
    Systeme --> User: code 403 : page d'erreur
end


@enduml
