@startuml authentification

actor User
boundary Systeme
database BDD

User -> Systeme: login() : l'utilisateur soumet ses informations
Systeme -> BDD: recherche d'un utilisateur correspondant
BDD --> Systeme : utilisateur trouvé
Systeme --> User: Connexion reussie

@enduml
